a=int(input())
b=int(input())
c=int(input())
d=int(input())
arr=[]
arr.append(a)
arr.append(b)
arr.append(c)
arr.append(d)
maxage=max(arr)
minage=max(arr)
print("The min IS ",min(arr))
print("The max age  IS ",max(arr))